project_id: '532658'
api_token_env: 'CROWDIN_PERSONAL_TOKEN'
pull_request_title: 'chore(i18n-crowdin): new crowdin translation 🌐'
commit_message: 'chore(i18n-crowdin): new translations for %original_file_name% (%language%)'
append_commit_message: false

files:
  - source: /i18n/en-US/**/*.json
    translation: /i18n/%locale%/**/%original_file_name%