export const DISCORD_CLIENT_TOKEN = Symbol('DISCORD_CLIENT');
export const DISCORD_CLIENT_CONFIG_TOKEN = 'DISCORD_CLIENT_CONFIG';
export const DISCORD_CLIENT_COMMANDS_TOKEN = 'DISCORD_CLIENT_COMMANDS_TOKEN';
export const DISCORD_CLIENT_INHIBITORS_TOKEN =
    'DISCORD_CLIENT_INHIBITORS_TOKEN';
export const DISCORD_CLIENT_LISTENERS_TOKEN = 'DISCORD_CLIENT_LISTENERS_TOKEN';
