version: '2'

services:
    api:
        image: varrock-stray-dog/api
        command: production:start
        env_file: ../.env
        ports:
            - '$EXPOSED_API_PORT:3000'
    bot:
        image: varrock-stray-dog/bot
        command: production:start
        env_file: ../.env
    redis:
        image: redis
    postgres:
        image: postgres
        environment:
            - 'POSTGRES_USER=$POSTGRES_USER'
            - 'POSTGRES_DB=$POSTGRES_NAME'
            - 'POSTGRES_PASSWORD=$POSTGRES_PASSWORD'
        ports:
            - '$EXPOSED_POSTGRES_PORT:5432'
