version: '2'

services:
  base:
    build:
      context: ../
      dockerfile: ./.docker/Dockerfile
    env_file: ../.env
    volumes:
      - ../:/opt/app
  api:
    extends: base
    command: start:api
    ports:
      - '$EXPOSED_API_PORT:3000'
  bot:
    extends: base
    command: start:bot
    ports:
      - '$EXPOSED_STUDIO_PORT:5555'
  web:
    extends: base
    command: start:web
    ports:
      - '$EXPOSED_WEB_PORT:4200'
  redis:
    image: redis
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=stray-dog
      - POSTGRES_DB=stray-dog
      - POSTGRES_PASSWORD=stray-dog
    ports:
      - '$EXPOSED_POSTGRES_PORT:5432'
