version: '2'

services:
    base:
        build:
            context: ../
            dockerfile: ./.docker/Dockerfile
        env_file: ../.env
        tty: true
        volumes:
            - ../:/opt/app
