export interface IPetMetaData {
    name: string;
    category: string;
    aliases: string[];
    asset: string;
    emoji: string[];
}

export const Pets: IPetMetaData[] = [
    {
        name: 'Pet chaos elemental',
        category: 'boss',
        aliases: ['Chaos elemental'],
        asset: 'Pet_chaos_elemental.png',
        emoji: ['Pet_chaos_elemental', '749362398376493066'],
    },
    {
        name: 'Pet dagannoth supreme',
        category: 'boss',
        aliases: ['dk supreme', 'supreme'],
        asset: 'Pet_dagannoth_supreme.png',
        emoji: ['Pet_dagannoth_supreme', '749362398342938634'],
    },
    {
        name: 'Pet dagannoth prime',
        category: 'boss',
        aliases: ['dk prime', 'prime'],
        asset: 'Pet_dagannoth_prime.png',
        emoji: ['Pet_dagannoth_prime', '749362397940154518'],
    },
    {
        name: 'Pet dagannoth rex',
        category: 'boss',
        aliases: ['dk rex', 'rex'],
        asset: 'Pet_dagannoth_rex.png',
        emoji: ['Pet_dagannoth_rex', '749362398317641818'],
    },
    {
        name: 'Pet penance queen',
        category: 'boss',
        aliases: ['barbarian assault', 'ba'],
        asset: 'Pet_penance_queen.png',
        emoji: ['Pet_penance_queen', '749362398040686684'],
    },
    {
        name: "Pet kree'arra",
        category: 'boss',
        aliases: ['armadyl', 'arma', 'kree'],
        asset: "Pet_kree'arra.png",
        emoji: ['Pet_kreearra', '749362398158258327'],
    },
    {
        name: 'Pet general graardor',
        category: 'boss',
        aliases: ['bandos', 'graardor'],
        asset: 'Pet_general_graardor.png',
        emoji: ['Pet_general_graardor', '749362398212653168'],
    },
    {
        name: 'Pet zilyana',
        category: 'boss',
        aliases: ['sara', 'saradomin', 'zily'],
        asset: 'Pet_zilyana.png',
        emoji: ['Pet_zilyana', '749362398334288003'],
    },
    {
        name: "Pet k'ril tsutsaroth",
        category: 'boss',
        aliases: ['zammy', 'zamorak', 'tsutsaroth'],
        asset: "Pet_k'ril_tsutsaroth.png",
        emoji: ['Pet_kril_tsutsaroth', '749362398393270352'],
    },
    {
        name: 'Baby mole',
        category: 'boss',
        aliases: ['mole'],
        asset: 'Baby_mole.png',
        emoji: ['Baby_mole', '749362284840747138'],
    },
    {
        name: 'Prince black dragon',
        category: 'boss',
        aliases: ['King black dragon', 'kbd'],
        asset: 'Prince_black_dragon.png',
        emoji: ['Prince_black_dragon', '749362398317641848'],
    },
    {
        name: 'Kalphite princess',
        category: 'boss',
        aliases: ['kq', 'kalphite', 'kalphite queen'],
        asset: 'Kalphite_princess.png',
        emoji: ['Kalphite_princess', '749362398305190038'],
    },
    {
        name: 'Pet smoke devil',
        category: 'boss',
        aliases: ['smoke', 'smoke devil'],
        asset: 'Pet_smoke_devil.png',
        emoji: ['Pet_smoke_devil', '749362398195875947'],
    },
    {
        name: 'Pet kraken',
        category: 'boss',
        aliases: ['kraken'],
        asset: 'Pet_kraken.png',
        emoji: ['Pet_kraken', '749362398162321409'],
    },
    {
        name: 'Pet dark core',
        category: 'boss',
        aliases: ['core', 'corp', 'corporeal beast'],
        asset: 'Pet_dark_core.png',
        emoji: ['Pet_dark_core', '749362398342807673'],
    },
    {
        name: 'Pet snakeling',
        category: 'boss',
        aliases: ['zurlah'],
        asset: 'Pet_snakeling.png',
        emoji: ['Pet_snakeling', '749362398003068999'],
    },
    {
        name: 'Chompy chick',
        category: 'other',
        aliases: ['chompy'],
        asset: 'Chompy_chick.png',
        emoji: ['Chompy_chick', '749362397952737313'],
    },
    {
        name: 'Venenatis spiderling',
        category: 'boss',
        aliases: ['vene'],
        asset: 'Venenatis_spiderling.png',
        emoji: ['Venenatis_spiderling', '749362398372298882'],
    },
    {
        name: 'Callisto cub',
        category: 'boss',
        aliases: [],
        asset: 'Callisto_cub.png',
        emoji: ['Callisto_cub', '749362398325899384'],
    },
    {
        name: "Vet'ion jr.",
        category: 'boss',
        aliases: ['vet'],
        asset: "Vet'ion_jr..png",
        emoji: ['Vetion_jr', '749362398426562570'],
    },
    {
        name: "Scorpia's offspring",
        category: 'boss',
        aliases: ['scorpia'],
        asset: "Scorpia's_offspring.png",
        emoji: ['Scorpias_offspring', '749362398414110740'],
    },
    {
        name: 'Tzrek-jad',
        category: 'boss',
        aliases: ['jad'],
        asset: 'Tzrek-jad.png',
        emoji: ['Tzrekjad', '749362398431019114'],
    },
    {
        name: 'Hellpuppy',
        category: 'boss',
        aliases: ['cerb', 'cerberus'],
        asset: 'Hellpuppy.png',
        emoji: ['Hellpuppy', '749362398296539297'],
    },
    {
        name: 'Abyssal orphan',
        category: 'boss',
        aliases: ['abyssal demon', 'sire'],
        asset: 'Abyssal_orphan.png',
        emoji: ['Abyssal_orphan', '749362284761186314'],
    },
    {
        name: 'Heron',
        category: 'skilling',
        aliases: ['fishing'],
        asset: 'Heron.png',
        emoji: ['Heron', '749362398208589946'],
    },
    {
        name: 'Rock golem',
        category: 'skilling',
        aliases: ['mining'],
        asset: 'Rock_golem.png',
        emoji: ['Rock_golem', '749362398485545127'],
    },
    {
        name: 'Beaver',
        category: 'skilling',
        aliases: ['woodcutting'],
        asset: 'Beaver.png',
        emoji: ['Beaver', '749362398334550026'],
    },
    {
        name: 'Baby chinchompa',
        category: 'skilling',
        aliases: ['chin', 'hunter'],
        asset: 'Baby_chinchompa.png',
        emoji: ['Baby_chinchompa', '749362284358533323'],
    },
    {
        name: 'Bloodhound',
        category: 'other',
        aliases: ['clue'],
        asset: 'Bloodhound.png',
        emoji: ['Bloodhound', '749362398300733521'],
    },
    {
        name: 'Giant squirrel',
        category: 'skilling',
        aliases: ['agility'],
        asset: 'Giant_squirrel.png',
        emoji: ['Giant_squirrel', '749362398321967215'],
    },
    {
        name: 'Tangleroot',
        category: 'skilling',
        aliases: ['farming', 'groot'],
        asset: 'Tangleroot.png',
        emoji: ['Tangleroot', '749362397990354955'],
    },
    {
        name: 'Rift guardian',
        category: 'skilling',
        aliases: ['runecrafting', 'tears of guthix', 'tog'],
        asset: 'Rift_guardian.png',
        emoji: ['Rift_guardian', '749362398212653127'],
    },
    {
        name: 'Rocky',
        category: 'skilling',
        aliases: ['balboa', 'thieving'],
        asset: 'Rocky.png',
        emoji: ['Rocky', '749362398296670309'],
    },
    {
        name: 'Phoenix',
        category: 'skilling',
        aliases: ['firemaking', 'wintertodt', 'wt'],
        asset: 'Phoenix.png',
        emoji: ['Phoenix', '749362398346870894'],
    },
    {
        name: 'Olmlet',
        category: 'boss',
        aliases: ['olm', 'chambers of xeric', 'cox'],
        asset: 'Olmlet.png',
        emoji: ['Olmlet', '749362398288412693'],
    },
    {
        name: 'Metamorphic dust',
        category: 'boss',
        aliases: ['challenge mode', 'cm', 'dust'],
        asset: 'Metamorphic_dust.png',
        emoji: ['Metamorphic_dust', '749362398351065098'],
    },
    {
        name: 'Skotos',
        category: 'boss',
        aliases: ['skotizo'],
        asset: 'Skotos.png',
        emoji: ['Skotos', '749362398401396897'],
    },
    {
        name: 'Jal-nib-rek',
        category: 'boss',
        aliases: ['nibler', 'inferno', 'zuk'],
        asset: 'Jal-nib-rek.png',
        emoji: ['Jalnibrek', '749362398003068940'],
    },
    {
        name: 'Herbi',
        category: 'skilling',
        aliases: ['herbiboar', 'herblore'],
        asset: 'Herbi.png',
        emoji: ['Herbi', '749362398300995656'],
    },
    {
        name: 'Noon/Dusk',
        category: 'boss',
        aliases: ['noon', 'dusk', 'grotesque'],
        asset: 'Noon.png',
        emoji: ['Noon', '749362398179229727'],
    },
    {
        name: 'Vorki',
        category: 'boss',
        aliases: ['vorkath'],
        asset: 'Vorki.png',
        emoji: ['Vorki', '749362398372298922'],
    },
    {
        name: "Lil' zik",
        category: 'boss',
        aliases: ['verzik', 'vitur', 'tob', 'theatre of blood'],
        asset: "Lil'_zik.png",
        emoji: ['Lil_zik', '749362398229692440'],
    },
    {
        name: 'Ikkle hydra',
        category: 'boss',
        aliases: ['hydra', 'alchemical hydra'],
        asset: 'Ikkle_hydra.png',
        emoji: ['Ikkle_hydra', '749362398233624677'],
    },
    {
        name: 'Sraracha',
        category: 'boss',
        aliases: ['sarachnis'],
        asset: 'Sraracha.png',
        emoji: ['Sraracha', '749362398397333634'],
    },
    {
        name: 'Youngllef',
        category: 'boss',
        aliases: ['gauntlet', 'hunleff'],
        asset: 'Youngllef.png',
        emoji: ['Youngllef', '749362398372298932'],
    },
    {
        name: 'Smolcano',
        category: 'boss',
        aliases: ['zalcano'],
        asset: 'Smolcano.png',
        emoji: ['Smolcano', '749362398342676511'],
    },
    {
        name: 'Little nightmare',
        category: 'boss',
        aliases: ['nightmare', 'ashihama'],
        asset: 'Little_nightmare.png',
        emoji: ['Little_nightmare', '749362397960994828'],
    },
    {
        name: "Lil' creator/Lil' Destructor",
        category: 'minigame',
        aliases: ['soul wars', 'destructor', 'creator'],
        asset: "Lil'_creator.png",
        emoji: ['Lil_creator', '801171183000748052'],
    },
    {
        name: 'Tiny tempor',
        category: 'minigame',
        aliases: ['temperos', 'tempy'],
        asset: 'Tiny_tempor.png',
        emoji: ['Tiny_tempor', '1007607628404363426'],
    },
    {
        name: 'Abyssal protector',
        category: 'minigame',
        aliases: ['protector', 'aby protector', 'rift'],
        asset: 'Abyssal_protector.png',
        emoji: ['Abyssal_protector', '1007607985683578930'],
    },
];
